# Copyright 2025 Advance Insight
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
{
    "name": "AgriOS",
    "summary": """Efficiently manage an farmer network""",
    "author": "Advance Insight",
    "website": "https://agrios.org",
    "category": "AgriOS",
    "version": "18.0.1.3.6",
    "license": "AGPL-3",
    "depends": [
        # Odoo Modules
        "account",
        "sale_management",
        "purchase",
        "stock",
        "hr",
        # OCA Modules
        "account_usability",
        # Agrios Modules
        "agrios_farmer",
    ],
    "data": [
        "security/security_groups.xml",
        "security/ir.model.access.csv",
        "security/securiry_rules.xml",
        "data/uoms.xml",
        "data/partner_categories.xml",
        "data/sequences.xml",
        "data/crons.xml",
        "wizard/multiple_confirm_draft_contracts_wizard.xml",
        "wizard/multiple_set_contracted_mapped_qty_wizard.xml",
        "wizard/bulk_contract_action_wizard.xml",
        "wizard/account_payment_register_views.xml",
        "views/farmer_group_views.xml",
        "views/season_views.xml",
        "views/training_views.xml",
        "views/certification_views.xml",
        "views/contract_views.xml",
        "views/res_partner_farmer_views.xml",
        "views/partner_views.xml",
        "views/partner_area_views.xml",
        "views/farmer_plot_crop_area_views.xml",
        "views/purchase_order_views.xml",
        "views/sale_order_views.xml",
        "views/product_views.xml",
        "views/res_config_settings_views.xml",
        "views/reports.xml",
        "views/account_journal.xml",
        "views/account_move.xml",
        "views/menus.xml",
    ],
    "demo": [
        "demo/res_partner_demo.xml",
        "demo/master_data.xml",
        "demo/products_general.xml",
        "demo/employee_department.xml",
        "demo/plots.xml",
        "demo/farmer_training.xml",
        "demo/certification.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "agrios/static/src/module/module_styles.scss",
            "agrios/static/src/lib/leaflet/leaflet.css",
            "agrios/static/src/lib/leaflet/leaflet.js",
            "agrios/static/src/lib/leaflet.draw/leaflet.draw.css",
            "agrios/static/src/lib/leaflet.draw/leaflet.draw.js",
            "agrios/static/src/components/**/*",
        ],
        "web._assets_primary_variables": [
            (
                "before",
                "web/static/src/scss/primary_variables.scss",
                "agrios/static/src/scss/primary_variables.scss",
            ),
        ],
    },
    "application": True,
    "installable": True,
    "auto_install": False,
    "post_init_hook": "post_init_hook",
    "uninstall_hook": "uninstall_hook",
    "sequence": -1,
}
