# -*- coding: utf-8 -*-
{
    'name': "AgriOS",
    'summary': """Efficiently manage an farmer network""",
    'description': """Database to register and manage farmers""",
    'author': "Advance Insight",
    'website': "https://www.advanceinsight.dev",
    'category': 'Advance Insight Product',
    'version': '18.0.1.3.2',
    'license': 'Other proprietary',
    'depends': [
        'contacts',
        'account',
        'sale_management',
        'purchase',
        'stock',
        'hr',
        'account_usability',
    ],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'security/securiry_rules.xml',
        'data/uoms.xml',
        'data/partner_categories.xml',
        'data/sequences.xml',
        'data/crons.xml',
        'data/country_location_levels.xml',
        'data/functions.xml',
        'wizard/multiple_confirm_draft_contracts_wizard.xml',
        'wizard/multiple_set_contracted_mapped_qty_wizard.xml',
        'wizard/bulk_contract_action_wizard.xml',
        'wizard/account_payment_register_views.xml',
        'wizard/agrios_data.xml',
        'views/season_views.xml',
        'views/administration_views.xml',
        'views/training_views.xml',
        'views/certification_views.xml',
        'views/interaction_views.xml',
        'views/contract_views.xml',
        'views/res_partner_farmer_views.xml',
        'views/partner_views.xml',
        'views/partner_area_views.xml',
        'views/farmer_plot_crop_area_views.xml',
        'views/res_users_views.xml',
        'views/purchase_order_views.xml',
        'views/sale_order_views.xml',
        'views/product_views.xml',
        'views/res_config_settings_views.xml',
        'views/reports.xml',
        'views/account_journal.xml',
        'views/account_move.xml',
        'views/highest_education_views.xml',
        'views/id_type_views.xml',
        'views/menus.xml',
    ],
    'demo': [
        'demo/master_data.xml',
        'demo/hierarchy.xml',
        'demo/products_general.xml',
        'demo/farmers.xml',
        'demo/users.xml',
        'demo/employee_department.xml',
        'demo/plots.xml',
        'demo/farmer_training.xml',
        'demo/farmer_interaction.xml',
        'demo/farmer_interaction_no_contract.xml',
        'demo/certification.xml',
        'demo/warehouse_stock.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'agrios/static/src/module/module_styles.scss',
            'agrios/static/src/lib/leaflet/leaflet.css',
            'agrios/static/src/lib/leaflet/leaflet.js',
            'agrios/static/src/lib/leaflet.draw/leaflet.draw.css',
            'agrios/static/src/lib/leaflet.draw/leaflet.draw.js',
            'agrios/static/src/components/**/*',
        ],
        'web._assets_primary_variables': [
            ('before', 'web/static/src/scss/primary_variables.scss', 'agrios/static/src/scss/primary_variables.scss'),
        ],
    },
    'application': True,
    'installable': True,
    'auto_install': False,
    'post_init_hook': 'post_init_hook',
    'uninstall_hook': 'uninstall_hook',
    'sequence': -1,
}