# -*- coding: utf-8 -*-
{
    'name': "Outgrower Management System",
    'summary': """Efficiently manage an outgrower network""",
    'description': """Database to register and manage outgrowers""",
    'author': "Advance Insight",
    'website': "https://www.advanceinsight.dev",
    'category': 'Advance Insight Product',
    'version': '18.0.1.3.2',
    'license': 'Other proprietary',
    'depends': [
        'contacts',
        'account',
        'sale_management',
        'purchase',
        'stock',
    ],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'security/securiry_rules.xml',
        'data/uoms.xml',
        'data/partner_categories.xml',
        'data/sequences.xml',
        'data/crons.xml',
        'data/country_location_levels.xml',
        'data/functions.xml',
        'wizard/multiple_confirm_draft_contracts_wizard.xml',
        'wizard/multiple_set_contracted_mapped_qty_wizard.xml',
        'wizard/bulk_contract_action_wizard.xml',
        'wizard/account_payment_register_views.xml',
        'views/season_views.xml',
        'views/administration_views.xml',
        'views/training_views.xml',
        'views/certification_views.xml',
        'views/interaction_views.xml',
        'views/contract_views.xml',
        'views/partner_views.xml',
        'views/partner_area_views.xml',
        'views/res_partner_subplot_views.xml',
        'views/res_users_views.xml',
        'views/purchase_order_views.xml',
        'views/sale_order_views.xml',
        'views/product_views.xml',
        'views/res_config_settings_views.xml',
        'views/reports.xml',
        'views/account_journal.xml',
        'views/account_move.xml',
        'views/menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'ai_oms/static/src/module/module_styles.scss',
            
            'ai_oms/static/src/lib/leaflet/leaflet.css',
            'ai_oms/static/src/lib/leaflet/leaflet.js',
            'ai_oms/static/src/lib/leaflet.draw/leaflet.draw.css',
            'ai_oms/static/src/lib/leaflet.draw/leaflet.draw.js',
            
            'ai_oms/static/src/components/**/*',
        ],
    },
    'application': True,
    'installable': True,
    'auto_install': False,
    'sequence': -1,
}